### ISSUE TITLE
缺少这两个库，能辛苦提供一下吗？ssl.lib;crypto.lib

### ISSUE THREAD

**Issue by greenjava1** [cbhust8025/ChromiumBase#1]
缺少这两个库，能辛苦提供一下吗？ssl.lib;crypto.lib
感谢！

**Comment by cbhust8025** [comment]
少了两个库，针对ssl的两个库，我放到了这里可以进行下载使用（仅包含32位release和debug版本）
https://share.weiyun.com/Pdhmsk0q
另外，这两个库也可以自行编译：参考文章【[【Chromium】如何提取Chromium的Base库（下）-腾讯云开发者社区-腾讯云](https://cloud.tencent.com/developer/article/2409791?from_column=20421&from=20421)】这里问题7有详细的编译流程，可自行编译需要的版本
